// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://uebdvnnwwfmwwsekubvh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVlYmR2bm53d2Ztd3dzZWt1YnZoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTgzMzk0NjIsImV4cCI6MjA3MzkxNTQ2Mn0.zjvBrC1op1w8kTRnIzo9Dra6D-Poq8Q1UQLMoiPn5Nw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});